# action.yml
name: "Levant Deploy"
author: "Darryl Mendillo"
description: "Template and deploy all nomad jobs matching regex in config"
branding:
  icon: "database"
  color: "red"
inputs:
  version:
    description: "Release version (tag)"
    required: true
  config:
    description: "deploy_config.yml file with all deployment settings"
    required: true
  nomad_addr:
    description: "target nomad deployment address"
    required: true
  deploy:
    description: "deploy the jobs after rendering. False will only render. Default = TRUE"
    required: false
    default: 'TRUE'

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    NOMAD_ADDR: ${{ inputs.nomad_addr }}
    VERSION: ${{ inputs.version }}
    DEPLOY_CONFIG: ${{ inputs.config }}
    DEPLOY: ${{ inputs.deploy }}