# action.yml
name: "Levant Deploy"
author: "Darryl Mendillo"
description: "Template and deploy all nomad jobs matching regex in config"
branding:
  icon: "database"
  color: "red"
inputs:
  version:
    description: "Release version (tag)"
    required: true
  config:
    description: "deploy_config.yml file with all deployment settings"
    required: true
  nomad_addr:
    description: "target nomad deployment address"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.nomad_addr }}
    - ${{ inputs.version }}
    - ${{ inputs.config }}
